# Generated by Django 2.2.5 on 2021-09-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoForm', '0002_alter_todo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_loginModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=25)),
                ('password', models.CharField(max_length=100)),
                ('save', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
