# Generated by Django 2.2.5 on 2021-09-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoForm', '0004_auto_20210924_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_raised', models.DateTimeField(default=True, editable=False)),
                ('refrence', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
