# Generated by Django 2.2.5 on 2021-09-29 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoForm', '0005_uservalidation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Todo_model',
        ),
        migrations.RenameModel(
            old_name='User_loginModel',
            new_name='Validation_model',
        ),
        migrations.DeleteModel(
            name='UserValidation',
        ),
    ]
